[core]
name:Gleamander
maxHp:2500
armour:300
mass:5000
price:2200,VE:800
radius:46
tags:guangyuan
buildSpeed:14s
fogOfWarSightRange:36
displayText:Gleamander
displayText_zh:光螈
displayDescription_zh:-陆军主力探雾单位\n-用身上的发光不稳定液体大范围照亮单位群体周边\n-无法攻击\n-需要保护的高血量单位\n-被敌人消灭会引爆不稳定液体导致自己的单位受损
displayDescription:-land's main fog detection unit\n-Use the light-emitting unstable liquid on the body to illuminate a large area around the unit group\n-Unable to attack\n- High-Hp units that need protection\n-Destroyed by the enemy will detonate unstable liquid causing damage to your unit
transportSlotsNeeded:12
[graphics]
image:Gleamander.png
scaleImagesTo:128
image_shadow:AUTO
shadowOffsetX:10
drawLayer:ground
shadowOffsetY:10
[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:true
canAttackUnderwaterUnits:false
disablePassiveTargeting:true
showRangeUIGuide:false
[movement]
movementType:OVER_CLIFF
moveSpeed:1.2
[placementRule_数量限制]
anyRuleInGroup:maxcunts 
searchTags:guangyuan
searchDistance:700
#searchOffsetX:-80
#searchOffsetY:-20
maxCount:2
cannotPlaceMessage: Only three units can exist in range. Too many of these units may cause the base to be destroyed
cannotPlaceMessage_zh:范围内仅可存在三个此单位 过多可能会导致死亡时基地被毁
[action_细胞分裂]
isLocked:true
isLockedMessage_zh:此单位禁用
isLockedMessage:This action is disabled for this unit
[leg_1]
x:-38
y:21
moveSpeed:4
rotateSpeed:3
heightSpeed:0.35
resetAngle:75
image_leg:bydleg.png
image_foot:foot.png
#draw_foot_on_top: true
#dust_effect: false

[leg_2]
x:38
y:21
copyFrom:1

[leg_3]
x:-38
y:-25
#x: -30
#y: -18
copyFrom:1
resetAngle:-45

[leg_4]
x:38
y:-25
#x: 30
#y: -18
copyFrom:1
resetAngle:-45

[turret_bomb]
x:0
y:0
canShoot:false
projectile:bloodbomb
[projectile_bloodbomb]
life:30
instant: true
friendlyFire: true
areaDamage:3600
explodeEffect:爆2
areaExpandTime:40
explodeOnEndOfLife:true
areaHitAirAndLandAtSameTime:true
areaRadius:560
largeHitEffect:true
targetGround:true
[action_111]
text:爆炸
description:爆炸
#isLocked:if self.hp > 5000
buildSpeed:0.05s
canPlayerCancel:false
spawnEffects:血1*29,血2*25
displayType:action
isVisible:false
fireTurretXAtGround_withOffset:0,0
allowMultipleInQueue:false
alwaysSinglePress:true
autoTriggerOnEvent:destroyed
fireTurretXAtGround:bomb
[effect_血1]
priority:low
life: 725
lifeRandom:12
attachedToUnit: false
color: #130077
scaleFrom:3
scaleTo:2.35
alpha: 0.5
fadeOut:true
drawUnderUnits:false
image:ROOT:EffectImages/Blood.png
dirSpeedRandom:3
dirOffsetRandom:5
hOffset:3
ySpeedRelativeRandom:3.4222
xSpeedRelativeRandom:3.3222
physicsGravity:0.054
physics:true
atmospheric:true
[effect_血2]
priority:low
life: 800
attachedToUnit: false
color: #003577
scaleFrom:3
scaleTo:2.45
lifeRandom:12
alpha: 0.5
fadeOut:true
drawUnderUnits:false
image:ROOT:EffectImages/Blood.png
dirSpeedRandom:3
dirOffsetRandom:5
hOffset:3
ySpeedRelativeRandom:3.4222
xSpeedRelativeRandom:3.3222
physicsGravity:0.07
physics:true
atmospheric:true
[effect_爆2]
priority:critical
total_frames:14
life: 200
attachedToUnit: false
color: #49FFF8
scaleFrom:25
scaleTo:31
alpha: 1
drawUnderUnits:false
animateFrameSpeed:0.2
animateFrameEnd:13
animateFrameStart:0
image:bombeffect.png

alsoPlaySound:Explosion.ogg