[core]



name:暴吸巨蚊
copyFrom: ROOT:bloodthirstySandstrom\airbug\tumorMozzie\肿瘤飞蚊.ini
displayText_en: Sanguirupt
displayText_zh: 血之破碎者
displayDescription: -dirstroy enemy units by sucking their blood\n-When hp drops to half, can activate passive skill Blood Explosion\n-Energy will enhance the damage of self-explosion and attack\n-Self-explosion damage can be stacked up to 100,000\n-Can use its proboscis to repair units
displayDescription_zh:-使用口器对敌人的身体进行毁灭性抽取\n-当血量降低到一半时可主动释放被动技能血爆\n-能量会增强自爆和攻击的伤害\n-自爆伤害最高可叠加到100,000\n-可以使用口器修复单位
maxHp:12000
price:860000,DNA=8500
nanoRepairSpeed:0.65
techLevel:3
mass:10
armour:120
isBuilder:true
canRepairBuildings:true
energyMax:100000
energyStartingPercentage:0
canRepairUnits:true
buildSpeed:92s
radius:30
canReclaimResources:true
transportSlotsNeeded:1
[graphics]
image:华丽暴吸巨蚊.png
image_wreak:华丽暴吸巨蚊死.png
teamColoringMode:disabled
scaleImagesTo: 76
[attack]
maxAttackRange:45

[projectile_射了]
areaDamage: 45
areaRadius:20
areaHitAirAndLandAtSameTime:true
buildingDamageMultiplier:25
[turret_射了]
resourceUsage: hp=-40,energy=-62
y:30
[turret_bomb]
x:0
y:0
canAttack:false
projectile:bloodbomb
[projectile_bloodbomb]
life:60
spawnUnit:SB_Spore*20
areaExpandTime:20
mutatorX_addResourcesAreaHit:spore:500,zxx:235
mutatorX_ifUnitWithoutTags:sb
explodeOnEndOfLife:true
areaRadius:640
areaHitAirAndLandAtSameTime:true
areaDamage:5000
[hiddenAction_伤害加强]
setUnitStats:shootDamageMultiplier += self.energy()
autoTrigger:true
#
[action_111]
text:Blood Explosion
text_zh:血爆
description:-Give up this superweapon\n-Suicidal explosive attack
description_zh:放弃此超级武器\n自杀式爆炸攻击
isLocked:if self.hp > 6000
isLockedMessage:此单位的健康值未小于50%（6000）\n请自行送死或者直接冲家
deleteSelf:true
buildSpeed:0.05s
canPlayerCancel:false
spawnEffects:爆1,Blood*62,Blood*62
displayType:action
fireTurretXAtGround_withOffset:0,0
allowMultipleInQueue:false
alwaysSinglePress:true
fireTurretXAtGround:bomb
addResources:hp=-100000

[effect_爆1]
priority:veryhigh
total_frames:14
life: 200
attachedToUnit: false
color: #00FF00
scaleFrom:29
scaleTo:36
alpha: 1
drawUnderUnits:false
animateFrameSpeed:0.2
animateFrameEnd:13
animateFrameStart:0