[core]


name: 灾厄母虫
displayText_zh:灾厄母虫
displayText:Disaster mother
maxHp:5300
armour:180
transportSlotsNeeded:20
displayDescription:-melee attack\n-Bloodthirsty Sandstorm tumorbug Empire's chief replicators with flesh-and-blood aberration ability to control the civilizations of Earth-like planets\n-The spore virus it carries transforms the captured Earth creatures, To become unindependently conscious tumor morphs\n-Unlike a copy of a bug soldier made by a flesh-and-blood buildings of a licensed template\n-They will only attack as weapons
displayDescription_zh:-近战攻击\n-嗜血沙尘暴虫族帝国用于控制类地行星的文明投放的具有血肉畸变能力的首领复制体\n-其携带的孢子病毒改造捕获的地球生物，变为无独立意识的瘤变造物\n-与血肉建筑被授权培育的模板复制原生士兵不同\n-它们只会作为兵器进攻
mass:2999
price:50000,DNA=6000
generation_resources:DNA=15,hp=15
generation_credits:24
startFallingWhenStartingUnit: true
isPickableStartingUnit:true
isBug:true
energyStartingPercentage:0
energyRegen:0.039
energyMax:75
radius:50
exit_x: 0
exit_y: 86
exit_moveAwayAmount:-30
exit_dirOffset: -180
tags:肿瘤,无视孢子,肿瘤建筑
[canBuild_1]
name: setRally, 肿瘤筑巢蚁,侦查蚁
[effect_bite]
priority:critical
animateFrameLooping:true
yOffsetRelativeRandom: 3
image: bitee.png
life: 30
alsoPlaySound:bite.ogg
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime:3
scaleFrom: 2.6
scaleTo: 2.2
alpha: 0.7
total_frames:3
animateFrameStart:0
animateFrameEnd:2
animateFrameSpeed:8
ySpeedRelative:4
[action_爆冲咬击]
isVisible:false
text:Sprintbite
text_zh:暴冲咬击
description:Active skill\nThe rapid body crashes forward while biting the enemys. This will cause a shadow to appear in the process\nDeals high armor damage
spawnEffects:bite
alwaysSinglePress:true
ai_isHighPriority:if self.energy() == 75 and self.isAttacking()
iconImage:Sprint bite.png
description_zh:主动技能\n快速的将身体朝前方撞的同时撕咬敌人 这个过程中会出现一道残影\n造成高额穿甲伤害
playAnimation:attacking
buildSpeed:0.3s
fireTurretXAtGround:Sprintbite
displayType:action
isVisible:true
highPriorityQueue:true
allowMultipleInQueue:false
fireTurretXAtGround_withOffset:0,90
isLockedMessage:能量不足 \nInadequate energy
isLocked:if self.energy() < 75
addResources:energy:-75
[hiddenAction_爆!]
autoTriggerOnEvent:destroyed
addResources:BaseUnitDeadCount:-2
spawnEffects:Blood1*37,Blood2*28,Blood3*38
[graphics]
image:dmother.png
image_wreak:mother_dead.png
scaleImagesTo:145
image_shadow:AUTO
drawLayer:ground2
shadowOffsetX:10
shadowOffsetY:10
dustEffect:true
lock_body_rotation_with_main_turret: true
total_frames:3
[attack]
showRangeUIGuide:false
isFixedFiring:true
aimOffsetSpread:0
shootDelay:52
maxAttackRange: 112
turretMultiTargeting:true
canAttack:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
canAttackFlyingUnits:true
isFixedFiring:true
isMelee:true
meleeEngangementDistance:60
[hiddenAction_从天而降]
setHeight:1200
autoTriggerOnEvent:created
[animation_moving]
start:0
end:0
speed:3
pingPong:false
onActions:move

[animation_idle]
start:0
end:0
speed:3
pingPong:false
onActions:idle

[animation_attacking]
start:1
end:2
speed:4
pingPong:false
onActions:attack

[ai]
useAsBuilder:true
useAsAttacker:false
[turret_近战]
x:0
y:0
#image:location.png
canAttackFlyingUnits:true
shoot_sound:large_gun_fire2
shoot_sound_vol:125
recoilOffset:5
recoilReturnTime:0.4s
projectile:啃咬
[projectile_啃咬]
instant:true
armourIgnoreAmount:300
mutatorX_directDamageMultiplier:10
mutatorX_ifUnitWithTags:步兵
life:0.5s
buildingDamageMultiplier:0.25
autoTargetingOnDeadTarget:true
areaDamage:600
areaRadius:45

[turret_Sprintbite]
x:0
y:60
#image:location.png
canAttackFlyingUnits:true
shoot_sound:large_gun_fire2
shoot_sound_vol:125
recoilOffset:40
recoilReturnTime:0.4s
canShoot:false
projectile:技能
[projectile_技能]
instant:true
mutatorX_addResourcesAreaHit:spore:160
mutatorX_ifUnitWithoutTags:无视孢子
armourIgnoreAmount:500
mutatorX_directDamageMultiplier:10
mutatorX_ifUnitWithTags:步兵
life:0.2s
autoTargetingOnDeadTarget:true
areaDamage:1200
areaRadius:45
largeHitEffect:true
buildingDamageMultiplier:0.34
[movement]
movementType:LAND
moveSpeed:0.3
moveAccelerationSpeed:10
maxTurnSpeed:1.6
[action_safeModeOff]
text:Cognitive filtering OFF
description:--Double-click to turn on filtering--\n-Some people may have adverse reactions to Bloodthirsty-sandstorm units image\n-When this setting is turned on\n-A layer of protection will be applied to their own Zerg units\n-Non-self units cannot be overwritten due to technical reasons

text_zh:认知过滤 OFF
description_zh:--双击开启过滤--\n-部分人群可能对虫族的贴图产生不良反应\n-开启此设置时 \n-会在自身虫族单位上覆盖一层保护\n-非自身单位由于技术原因无法覆盖
buildSpeed:0s
iconExtraImage:ROOT:Icons/Actions/FilteringOFF.png
isVisible:if self.Resource('safeMode') < 1
isLocked:if self.Resource('safeMode') > 0
isActive:if self.Resource('safeMode') < 1
displayType:action
addResources:safeMode:1
pos:0

[action_safeModeOn]

text:Cognitive filtering ON
description:--Double-click to turn on filtering--\n-Some people may have adverse reactions to Bloodthirsty-sandstorm units image\n-When this setting is turned on\n-A layer of protection will be applied to their own Zerg units\n-Non-self units cannot be overwritten due to technical reasons

text_zh:认知过滤 ON
description_zh:--双击关闭过滤--\n-部分人群可能对虫族的贴图产生不良反应\n-开启此设置时 \n-会在自身虫族单位上覆盖一层保护\n-非自身单位由于技术原因无法覆盖
buildSpeed:0s
isGuiBlinking:true
iconExtraImage:ROOT:Icons/Actions/FilteringON.png
isVisible:if self.Resource('safeMode') > 0
isLocked:if self.Resource('safeMode') < 1
isActive:if self.Resource('safeMode') > 0
displayType:action
addResources:safeMode:-1
pos:0
[global_resource_safeMode]
hidden:true
[leg_1]
image_leg:leg.png
drawUnderAllUnits:true
image_foot:foot.png
image_foot_shadow:SHADOW:foot.png
x:-56
y:-53
attach_y:-20
moveSpeed:7
dust_effect:true
heightSpeed:0.25
holdDisMax:4000
resetAngle:0
#腿脚旋转速度:9
favourOppositeSideNeighbours:true
attach_x:-20
[leg_2]
copyFrom:1
x:56
y:-53
attach_y:20
attach_x:-20
[leg_3]
copyFrom:2
x:56
y:53
attach_y:-20
attach_x:20
[leg_4]
copyFrom:3
x:-56
y:53
attach_y:-20
attach_x:-20