[core]
name:混乱蝾螈怪

displayText:Chaos Salamander
displayText_zh:混乱蝾螈怪

displayDescription: 1
displayDescription_zh: 点击输入文本

maxHp:3000
maxShield:1500
shieldRegen:19
mass:3000
price:2100,VE:740
radius:30
buildSpeed:15s

[graphics]
image:ChaosSalamander.png
image_wreak:base_dead.png
scaleImagesTo:60
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false

[movement]
movementType:OVER_CLIFF
moveSpeed:1.22
maxTurnSpeed:1.56

[turret_泡]
x:0
y:12
image:炮塔.png
idleDir:10


[leg_1]
x: -28
y: 32
moveSpeed: 2
rotateSpeed: 2
resetAngle: 75
image_leg:  bydleg.png
image_foot: foot.png
#draw_foot_on_top: true
#dust_effect: false

[leg_2]
x: 28
y: 32
copyFrom: 1

[leg_3]
x: -28
y: 6
#x: -30
#y: -18
copyFrom: 1
resetAngle: -45

[leg_4]
x: 28
y: -6
#x: 30
#y: -18
copyFrom: 1
resetAngle: -45