[core]



name:虚空抽取器T2
displayText:Void Extractor T2
displayText_zh:虚空抽取器 T2
displayDescription:-Produces symbiotic buildings that grow channels above resource pools,\n-Bluehole Floating Beasts symbiotically extract resources from the pool through gravity
displayDescription_zh:-在资源池上方制造通道生长的共生体建筑，\n-蓝洞悬浮兽与其共生，通过引力从池中抽取资源

maxHp:3000
generation_resources:VE=30
mass:100
price:1500,VE=600
radius:25
generation_credits:35
buildSpeed:20s
generation_delay:60
placeOnlyOnResPool:true
selfRegenRate:0.25
isBuilding:true
#此代码规定建筑范围
footprint:0,0,0,0
constructionFootprint:0,0,0,0
[graphics]
image:VoidmineT2.png
scaleImagesTo:71
image_wreak:basedead2.png
total_frames:4
animation_idle_start:0
animation_idle_end:3
animation_idle_speed:8
animation_idle_pingPong:false
animation_idle_scale_start:1
animation_idle_scale_end:1.005
image_back:voidmineback.png
[attack]
canAttack:false
[movement]
movementType:BUILDING

[effect_jj]
priority:veryhigh
stripIndex:effects
frameIndex:0
life:180
fadeOut:true
attachedToUnit:false
color:#0000FF
fadeInTime:50
scaleFrom:1
scaleTo:10
alpha:0.9
drawUnderUnits:false
hOffsetRandom:0.15
atmospheric:true
dirOffsetRandom:0
shadow:true
yOffsetRelative:10
xOffsetRelativeRandom:0
yOffsetRelativeRandom:0
xSpeedAbsoluteRandom:0
ySpeedAbsoluteRandom:1
[ai]
buildPriority:1
noneInBaseExtraPriority:1
noneGlobalExtraPriority:1
maxEachBase:20
maxGlobal:200




[arm_1]
image_end:back1.png
spinRate:10
drawUnderAllUnits:true
x:0
y:0