[core]

name:光刃收割者
displayText:Lighto Harvester
displayText_zh:光刃收割者

displayDescription_zh:-控制着邪恶魔法的虚空蛞蝓\n-对地释放可以破甲的结晶光镰攻击\n-移动速度中等
displayDescription:- The blueVoid Slug that controls darkmagic.\n-Release the armor damage multiple of crystallized light sickle attack on land enemy\n-medium moving speed
armour:40
maxHp:1500
mass:5900
price:1600,VE=800
buildSpeed:13s
radius:21

[movement]
movementType:LAND
moveSpeed:1.5
moveAccelerationSpeed:6
maxTurnSpeed:2
turnAcceleration:4

[graphics]
image:Lighto Harvester.png
image_wreak:base_dead.png
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2
scaleImagesTo:57
total_frames:7

[animation_moving]
start:0
end:1
speed:3
pingPong:false
onActions:move

[animation_idle]
start:0
end:0
speed:3
pingPong:false
onActions:idle

[animation_attacking]
start:2
end:6
speed:4
pingPong:false
onActions:attack

[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
maxAttackRange:220
isFixedFiring:true

[effect_镰刀解体]
life:50
image:breakup.png
priority:critical
total_frames:5
alsoPlaySound:sickle breakup.wav
animateFrameStart:0
animateFrameEnd:4
dirOffsetRandom:20
fadeOut:true
scaleFrom:0.8
scaleTo:0.9
alpha:0.8
animateFrameSpeed:0.3

[effect_结晶镰刀]
life:600
priority:critical
total_frames:11
imageShadow:SHADOW:sickle.png
attachedToUnit:true
fadeOut:true
shadow:true
scaleFrom:1.2
scaleTo:1.3
alpha:1.4
image:sickle.png
animateFrameStart:0
animateFrameEnd:10
animateFrameSpeed:0.5
animateFramePingPong:true

[effect_结晶镰刀拓维]
life:20
priority:high
total_frames:11
imageShadow:SHADOW:sickle.png
attachedToUnit:false
fadeOut:true
shadow:true
scaleFrom:0.7
scaleTo:0.8
alpha:0.46
image:sickle.png
color:#4682B4
animateFrameStart:0
animateFrameEnd:10
animateFrameSpeed:0.5
animateFramePingPong:true

[projectile_镰刀]
explodeOnEndOfLife:true
shieldDefectionMultiplier:0.35
shieldDamageMultiplier:2.3
explodeEffectOnShield:镰刀解体
explodeEffect:镰刀解体
trailEffect:结晶镰刀拓维
trailEffectRate:5.3
autoTargetingOnDeadTarget:true
areaDamage:90
directDamage:120
areaRadius:26
invisible:true
speed:3
life:5s
lightCastOnGround:true
targetSpeed:70
drawUnderUnits:true
drawSize:1.3
effectOnCreate:结晶镰刀

[turret_光镰]
x:0
y:24
canAttackFlyingUnits:false
image:NONE
shoot_sound:sickle attack.wav
shoot_sound_vol:75
shoot_light:#080053


#BingBong:i miss my wife