[core]


name:资金交易所
displayText:War Command Post
displayText_zh:战争指挥所
displayDescription:-Distributes general funds\n-Can use funds to launch healing bullets\n-Or empty fund blocks to allies
displayDescription_zh:-分发通用资金\n-可使用资金发射具有治疗作用的子弹\n-或者空投资金块给友军
altNames:MoneyExchange
maxHp:2500
copyFrom:发射资金块.lxt,heal.lxt,rea.lxt
#lxt Layered eXtension Template 分层扩展模板
isBuilding:true
mass:19088
price:250,MAC=25
radius:45
buildSpeed:25s
footprint:-2,-2,2,2
constructionFootprint:-2,-2,2,3
[graphics]
teamColoringMode:hueAdd
image:base.png
image_wreak:dead.png
image_shadow:AUTO
shadowOffsetX:3
shadowOffsetY:3
imageScale:1.25
total_frames:2
animation_idle_start:0
animation_idle_end:1
animation_idle_speed:5
animation_idle_pingPong:false
[attack]
canAttack:false
maxAttackRange:230000
[movement]
movementType:BUILDING
[ai]
buildPriority:1
noneInBaseExtraPriority:1.25
noneGlobalExtraPriority:1.5
maxEachBase:3
maxGlobal:30