name: Extract ZIP and Commit Changes

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  extract-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史（避免提交问题）

      - name: Find and extract ZIP files
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          
          # 查找并解压 ZIP 文件
          for zipfile in *.zip; do
            if [ -f "$zipfile" ]; then
              echo "Extracting $zipfile..."
              unzip -o "$zipfile"
              echo "Removing $zipfile..."
              rm "$zipfile"
            fi
          done
          
          if [ ! -f *.zip ]; then
            echo "No ZIP files found in the root directory."
          fi

      - name: Commit changes (if any)
        id: commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add .
          
          if git diff --quiet --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Auto-commit: Extracted ZIP files and removed originals"
            git push
            echo "Changes committed and pushed."
          fi
